-- SQL script to populate the 'stocks' table with a list of stock symbols, names, and exchanges.
INSERT INTO stocks (symbol, name, exchange)
VALUES ('AAPL', 'Apple Inc.', 'NASDAQ'),
       ('TSLA', 'Tesla, Inc.', 'NASDAQ'),
       ('AMZN', 'Amazon.com, Inc.', 'NASDAQ'),
       ('MSFT', 'Microsoft Corporation', 'NASDAQ'),
       ('NVDA', 'NVIDIA Corporation', 'NASDAQ'),
       ('GOOGL', 'Alphabet Inc. Class A', 'NASDAQ'),
       ('META', 'Meta Platforms, Inc.', 'NASDAQ'),
       ('NFLX', 'Netflix, Inc.', 'NASDAQ'),
       ('JPM', 'JPMorgan Chase & Co.', 'NYSE'),
       ('V', 'Visa Inc.', 'NYSE'),
       ('BAC', 'Bank of America Corporation', 'NYSE'),
       ('AMD', 'Advanced Micro Devices, Inc.', 'NASDAQ'),
       ('PYPL', 'PayPal Holdings, Inc.', 'NASDAQ'),
       ('DIS', 'The Walt Disney Company', 'NYSE'),
       ('T', 'AT&T Inc.', 'NYSE'),
       ('PFE', 'Pfizer Inc.', 'NYSE'),
       ('COST', 'Costco Wholesale Corporation', 'NASDAQ'),
       ('INTC', 'Intel Corporation', 'NASDAQ'),
       ('KO', 'Coca-Cola Company', 'NYSE'),
       ('TGT', 'Target Corporation', 'NYSE'),
       ('NKE', 'Nike, Inc.', 'NYSE'),
       ('SPY', 'SPDR S&P 500 ETF Trust', 'NYSE'),
       ('BA', 'The Boeing Company', 'NYSE'),
       ('BABA', 'Alibaba Group Holding Limited', 'NYSE'),
       ('XOM', 'Exxon Mobil Corporation', 'NYSE'),
       ('WMT', 'Walmart Inc.', 'NYSE'),
       ('GE', 'GE Aerospace', 'NYSE'),
       ('CSCO', 'Cisco Systems, Inc.', 'NASDAQ'),
       ('VZ', 'Verizon Communications Inc.', 'NYSE'),
       ('JNJ', 'Johnson & Johnson', 'NYSE'),
       ('CVX', 'Chevron Corporation', 'NYSE'),
       ('PLTR', 'Palantir Technologies Inc.', 'NYSE'),
       ('SQ', 'Block, Inc.', 'NYSE'),
       ('SHOP', 'Shopify Inc.', 'NYSE'),
       ('SBUX', 'Starbucks Corporation', 'NASDAQ'),
       ('SOFI', 'SoFi Technologies, Inc.', 'NASDAQ'),
       ('HOOD', 'Robinhood Markets, Inc.', 'NASDAQ'),
       ('RBLX', 'Roblox Corporation', 'NYSE'),
       ('SNAP', 'Snap Inc.', 'NYSE'),
       ('UBER', 'Uber Technologies, Inc.', 'NYSE'),
       ('FDX', 'FedEx Corporation', 'NYSE'),
       ('ABBV', 'AbbVie Inc.', 'NYSE'),
       ('ETSY', 'Etsy, Inc.', 'NASDAQ'),
       ('MRNA', 'Moderna, Inc.', 'NASDAQ'),
       ('LMT', 'Lockheed Martin Corporation', 'NYSE'),
       ('GM', 'General Motors Company', 'NYSE'),
       ('F', 'Ford Motor Company', 'NYSE'),
       ('RIVN', 'Rivian Automotive, Inc.', 'NASDAQ'),
       ('LCID', 'Lucid Group, Inc.', 'NASDAQ'),
       ('CCL', 'Carnival Corporation & plc', 'NYSE'),
       ('DAL', 'Delta Air Lines, Inc.', 'NYSE'),
       ('UAL', 'United Airlines Holdings, Inc.', 'NASDAQ'),
       ('AAL', 'American Airlines Group Inc.', 'NASDAQ'),
       ('TSM', 'Taiwan Semiconductor Manufacturing Company Limited', 'NYSE'),
       ('SONY', 'Sony Group Corporation', 'NYSE'),
       ('ET', 'Energy Transfer LP', 'NYSE'),
       ('NOK', 'Nokia Oyj', 'NYSE'),
       ('MRO', 'Marathon Oil Corporation', 'NYSE'),
       ('COIN', 'Coinbase Global, Inc.', 'NASDAQ'),
       ('SIRI', 'Sirius XM Holdings Inc.', 'NASDAQ'),
       ('RIOT', 'Riot Platforms, Inc.', 'NASDAQ'),
       ('CPRX', 'Catalyst Pharmaceuticals, Inc.', 'NASDAQ'),
       ('VWO', 'Vanguard FTSE Emerging Markets ETF', 'NASDAQ'),
       ('SPYG', 'SPDR Portfolio S&P 500 Growth ETF', 'NASDAQ'),
       ('ROKU', 'Roku, Inc.', 'NASDAQ'),
       ('BIDU', 'Baidu, Inc.', 'NASDAQ'),
       ('DOCU', 'DocuSign, Inc.', 'NASDAQ'),
       ('ZM', 'Zoom Video Communications, Inc.', 'NASDAQ'),
       ('PINS', 'Pinterest, Inc.', 'NYSE'),
       ('TLRY', 'Tilray Brands, Inc.', 'NASDAQ'),
       ('WBA', 'Walgreens Boots Alliance, Inc.', 'NASDAQ'),
       ('MGM', 'MGM Resorts International', 'NYSE'),
       ('NIO', 'NIO Inc.', 'NYSE'),
       ('C', 'Citigroup Inc.', 'NYSE'),
       ('GS', 'The Goldman Sachs Group, Inc.', 'NYSE'),
       ('WFC', 'Wells Fargo & Company', 'NYSE'),
       ('ADBE', 'Adobe Inc.', 'NASDAQ'),
       ('PEP', 'PepsiCo, Inc.', 'NASDAQ'),
       ('UNH', 'UnitedHealth Group Incorporated', 'NYSE'),
       ('CARR', 'Carrier Global Corporation', 'NYSE'),
       ('FUBO', 'fuboTV Inc.', 'NYSE'),
       ('HCA', 'HCA Healthcare, Inc.', 'NYSE'),
       ('BILI', 'Bilibili Inc.', 'NASDAQ'),
       ('RKT', 'Rocket Companies, Inc.', 'NYSE');


CREATE INDEX idx_historical_symbol ON historical_data(symbol);



